const STORAGE_KEY="lingxi-paper-horse-found";
const base={home:{no:"01/24",title:"小店首页",body:`<div class="shop-hero"><div><p class="eyebrow">临溪镇老街口 向河第二间</p><h2>临溪纸马铺</h2><p>本铺承接纸马、纸屋、纸轿、香烛、冥包代写。七月将近，镇上人多事杂，来店请先取号。</p><p>若有旧账、旧收据、旧名帖要查，请在本站搜索框输入对应姓名或物件名。掌柜年纪大，搜错字便找不到。</p><p class="back-note"><strong>新贴告示：</strong>近日有人询问三年前的沈婉，请勿在店内争吵。另，河门相关旧俗请看镇公所公告。</p><div class="tag-row"><span class="tag">沈婉</span><span class="tag">河门</span><span class="tag">纸马</span></div></div><div class="river-map"><span class="pin one"></span><span class="pin two"></span></div></div>`},goods:{no:"02/24",title:"纸扎目录",body:`<h2>纸扎目录</h2><p>纸马一匹二十六，纸轿一顶四十八，纸屋按间数另算。代写冥包需报生辰、籍贯、收件人旧名。</p><table class="ledger"><tr><th>品名</th><th>备注</th><th>取货</th></tr><tr><td>青面纸马</td><td>给水路远行者用，马眼不可点黑。</td><td>隔日</td></tr><tr><td>白伞</td><td>临溪旧俗称遮阳，实际用于遮名。</td><td>当日</td></tr><tr><td>冥包代写</td><td>旧名不详者不可接单，除非有柳树边的签押。</td><td>三日</td></tr></table><p>掌柜批注：问白伞的客人多半不是来买伞。若问柳树，就说库房漏水，账本不在。</p>`},notice:{no:"03/24",title:"节俗公告",body:`<h2>节俗公告</h2><p><strong>2026/08/02：</strong>七月半临近，纸马铺延长营业至夜里九点。</p><p><strong>2026/07/29：</strong>镇公所通知，今年不举行开河门仪式。任何私设河灯、纸马、白伞队伍者，后果自负。</p><p><strong>2023/08/30：</strong>因河堤维修，临溪老渡口暂停通行。请勿接近柳树渡、旧祠后门及河床底舱。</p><p>旧公告的落款被人刮掉了，只留下一个朱砂印：<span class="stamp">回潮前撤</span></p>`},room:{no:"04/24",title:"后屋照片",body:`<h2>后屋照片</h2><p>后屋不对外开放。照片中可见纸马骨架、竹篾、裁纸刀、河灯模具，以及一只被朱砂线缠住的旧木箱。</p><p>木箱侧面写着“沈家旧账”，下方还有一行更淡的字：<span class="redacted">底舱勿开</span></p><p>若你能看见被涂黑的字，也许该查一查它。</p>`}};
const records=[
["receipt","05/24","沈婉寄来的旧收据",["沈婉"],"一张三年前的纸马铺收据，背面写着不要开河门。",`<h2>沈婉寄来的旧收据</h2><p>日期：2023年8月28日。品名：青面纸马两匹，白伞一把，冥包代写四封。</p><p>付款人写的是沈婉，取货人却写着“沈知遥”。你从未在三年前来过临溪。</p><p class="back-note">收据背面：别让他们在七月半开河门。若我失踪，先查纸马，再查柳树。</p>`],
["rivergate","06/24","临溪镇志：河门条",["河门"],"镇志里对开河门的解释过于干净。",`<h2>临溪镇志：河门条</h2><p>临溪河旧称“回水”。每十二年水脉改向，须在七月半夜开河门，放纸马、河灯、白伞，使亡者循水路归乡。</p><p>镇志新版删除了“替身”二字。旧版边角仍可见残句：凡水不退，必有人代渡。</p><p>条目末尾引用《临溪民俗志》，又提到已废弃地点：柳树渡。</p>`],
["paperhorse","07/24","纸马制作说明",["纸马"],"普通纸马说明里混入了水路送人的禁忌。",`<h2>纸马制作说明</h2><p>陆路用红鬃，水路用青面。青面纸马需在颈侧留一寸空白，写旧名，不写今名。</p><p>若纸马配白伞，代表“人未到，名先到”。</p><p>说明页最下方有一枚小印：供货单见内账。</p>`],
["willow","08/24","柳树渡旧照片",["柳树","柳树渡"],"旧渡口照片背后藏着沈婉最后一次出现的位置。",`<h2>柳树渡旧照片</h2><p>照片拍摄于2023年8月30日凌晨。河边站着五个人，四个人打白伞，最后一个人只有被雨水糊开的轮廓。</p><p>照片背面写着：沈婉到过这里。她说底舱里有活人的呼吸声。</p><p>右下角压着一片干枯柳叶，叶脉上用朱砂写了“青绳”。</p>`],
["umbrella","09/24","白伞订货记录",["白伞"],"白伞被用来遮住不该出现的名字。",`<h2>白伞订货记录</h2><p>2023年8月，共售出白伞十九把，其中十七把没有付款记录，只在备注写“替镇公所暂收”。</p><table class="ledger"><tr><td>8月27日</td><td>白伞四把</td><td>柳树渡</td></tr><tr><td>8月28日</td><td>白伞一把</td><td>沈婉</td></tr><tr><td>8月30日</td><td>白伞十二把</td><td>回潮前</td></tr></table><p>掌柜写：伞不是遮雨，是遮名。名一遮，族谱就能改。</p>`],
["ghostpack","10/24","冥包代写名单",["冥包","代写冥包"],"代写名单里出现了仍然活着的人。",`<h2>冥包代写名单</h2><p>沈婉圈出了四个名字，旁边写着“这些人没有死”。</p><p>其中一个名字是周砚，1999年生，2023年8月29日登记为溺亡。镇上户籍系统里，他同日迁出。</p><p>沈婉留下的下一条线索只有两个字：族谱。</p>`],
["ledger","11/24","沈家旧账",["账本","旧账","沈家"],"沈家不是第一次和纸马铺发生关系。",`<h2>沈家旧账</h2><p>旧账从1987年开始，几乎每十二年出现一次“沈家补纸马”。备注怪异：借名、还名、换灯、压潮。</p><p>2011年的账页夹着一张照片，年轻的纸马铺老板站在河边，身后是沈婉的母亲。</p><p>2023年账页被撕去半张，残留词：底舱、青绳、活口。</p>`],
["folkbook","12/24","临溪民俗志节选",["民俗志"],"民俗志把祭祀写成了交换身份的流程。",`<h2>临溪民俗志节选</h2><p>开河门旧仪分三步：点马眼，撑白伞，放旧名。旧名入水，新名上岸。</p><p>外乡记录者批注：此俗疑与灾年逃户、户籍冒名有关。所谓河神，不过是集体沉默的名字。</p><p>节选末尾被剪掉一段，只剩标题：替身法。</p>`],
["supply","13/24","供货单",["供货单"],"纸马铺购买的不是纸，而是可以沉入水底的东西。",`<h2>供货单</h2><p>供货商：临溪船厂旧库。物品：防水油布、铅块、青绳、空白户籍夹、旧式印泥。</p><p>纸马铺没有船，却每十二年向船厂结一次账。2023年订单备注：底舱加固，回潮后拆。</p><p>发票抬头不是纸马铺，而是“临溪河祭筹备小组”。</p>`],
["rope","14/24","青绳",["青绳"],"青绳不是捆纸马的，是捆人的。",`<h2>青绳</h2><p>青绳浸过桐油，遇水不松。店里说它用来扎纸马骨架，但账本里每次青绳长度都刚好够绑十二个人。</p><p>沈婉写：他们不一定杀人。他们让人换名，再让旧名死掉。</p><p>青绳标签背面有库位：底舱三号。</p>`],
["cabin","15/24","底舱三号",["底舱"],"旧船底舱里曾经关过人。",`<h2>底舱三号</h2><p>底舱三号位于废弃渡船“临水号”。船体被拖到柳树渡下游，名义上作民俗展陈，实际没有开放过。</p><p>舱壁划痕记录了十二个短句，其中一个写：我是沈婉，不是沈知遥。</p><p>这句话被人用朱砂盖住，又在旁边写：错了，她是替身。</p>`],
["genealogy","16/24","族谱页",["族谱"],"族谱里同一行出现了两个沈知遥。",`<h2>族谱页</h2><p>沈家族谱2023年重修。沈婉一栏被划掉，旁注“出水不归”。沈知遥一栏下方多了一行小字：河门后补名。</p><p>你出生在外地，族谱里却把你记成“临溪长房女”。这是替身手续的一部分。</p><p>修谱人落款：陈守铺。</p>`],
["keeper","17/24","陈守铺的留言",["陈守铺"],"纸马铺老板承认自己帮他们保存假名。",`<h2>陈守铺的留言</h2><p>我守的不是铺，是这些人的旧名。镇上每十二年要一个替身，不是给河神，是给活人。</p><p>有人想逃债，有人想换身份，有人想让死人继续领钱。河祭只是他们用来吓住外人的皮。</p><p>沈婉查到了名单，所以他们要把她写成你。她若成了沈知遥，你就会在账上死掉。</p>`],
["news","18/24","三年前的新闻剪报",["剪报","新闻"],"新闻里所有关键时间都对不上。",`<h2>三年前的新闻剪报</h2><p>《临溪晚报》：2023年8月31日凌晨，柳树渡一名年轻女子落水失踪。警方初步判断为意外。</p><p>剪报下方手写：错。8月30日晚上她还在底舱。31日凌晨失踪的是旧名，不是人。</p><p>另有一条短讯提到：周砚家属拒领死亡证明。</p>`],
["zhouyan","19/24","周砚的匿名留言",["周砚"],"一个被登记为死人者留下了新的线索。",`<h2>周砚的匿名留言</h2><p>如果你是沈知遥，不要回临溪住店。你一刷身份证，他们就知道替身回来了。</p><p>沈婉活着。她让我留一句话：回潮那天，水会把旧名送回来。</p><p>她还说，最后别搜她的名字，要搜开河门。</p>`],
["substitute","20/24","替身法",["替身"],"所谓替身法，是一套伪装成民俗的身份替换流程。",`<h2>替身法</h2><p>替身并非献祭。真正被献出去的是名字、户籍、债务、罪责。旧名写进冥包，现名撑伞过河，纸马载走记录。</p><p>若替身本人不到场，则取其近亲旧物代替。沈婉寄给你的收据，就是为了证明他们已经开始取你的名。</p><p>替身法最后一步叫回潮。</p>`],
["backtide","21/24","回潮",["回潮"],"回潮是所有假名最怕的时刻。",`<h2>回潮</h2><p>临溪河每逢暴雨倒灌，旧渡口水位逆涨。老人说回潮会把不该沉的东西送回岸边。</p><p>2023年回潮后，岸边出现过十二只空冥包。每只里面都有活人的身份证复印件。</p><p>沈婉在最后一只冥包里放了录音卡，文件名是：开河门。</p>`],
["audio","22/24","录音卡转写",["录音卡"],"录音中沈婉说出了她为什么没有露面。",`<h2>录音卡转写</h2><p>“知遥，如果你听到这里，说明他们已经把你写进账本。我不能回家，也不能报警。镇上有人在系统里等我的名字出现。”</p><p>“陈守铺帮过他们，也帮过我。他把名单拆成二十四页，只要你找到最后一页，就知道该把账本交给谁。”</p><p>录音末尾是很长的水声，水声里有人反复念：开河门。</p>`],
["openriver","23/24","开河门",["开河门"],"最后的入口打开了。",`<h2>开河门</h2><p>页面加载很慢，像有水从屏幕后面渗出来。纸马铺的招牌变成黑底朱字：旧名归档，新名上岸。</p><p>档案显示，三年前共有十二人通过河祭替换身份。沈婉不是受害者名单中的死人，她是第十三个名字：负责替你“上岸”的活替身。</p><p>她拒绝了。于是镇上决定让你亲自回来，补完这场仪式。</p><p>页面底部出现一封信：沈婉来信。</p>`],
["letter","24/24","沈婉来信",["来信","沈婉来信"],"真相页。沈婉仍活着，但她留下了一个选择。",`<h2>沈婉来信</h2><p>知遥：</p><p>如果你找到这里，别急着来临溪。把纸马铺网站的二十四页保存下来，连同沈家旧账、供货单、族谱页一起交给外地警方。不要交给镇上任何人。</p><p>陈守铺不是清白的。他替他们写过很多死人，也替我藏过三年。他说自己守铺，是因为年轻时也从河里换过一个名字。</p><p>我还活着。周砚也活着。可只要账本没公开，我们都只能做已经死掉的人。</p><p class="back-note">你可以报警，也可以烧掉账本。可七月半快到了。河门不开，他们会来找你；河门一开，更多人的名字会沉下去。</p><p><span class="stamp">终</span></p>`]
].map(([id,no,title,keywords,summary,body])=>({id,no,title,keywords,summary,body}));
const kw=new Map;records.forEach(r=>r.keywords.forEach(k=>(kw.get(k)||kw.set(k,[]).get(k)).push(r)));
const $=s=>document.querySelector(s),content=$("#content"),foundList=$("#found-list"),counter=$("#page-counter"),modal=$("#result-modal"),mt=$("#modal-title"),mb=$("#modal-body"),input=$("#search-input"),tabs=[...document.querySelectorAll(".tab")];let found=load(),cur="home",installPrompt=null;
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||["home","goods","notice","room"]}catch{return["home","goods","notice","room"]}}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(found))}function esc(s){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function mark(id){if(!found.includes(id)){found.push(id);save()}}function doc(d){content.innerHTML=`<div class="doc"><div class="doc-head"><p class="eyebrow">临溪纸马铺档案</p><p class="page-no">${d.no}</p></div>${d.body}</div>`;counter.textContent=d.no}function byId(id){return base[id]||records.find(r=>r.id===id)}function title(id){return byId(id)?.title||id}function no(id){return byId(id)?.no||"--/24"}function list(){let order=id=>Number(no(id).slice(0,2))||99;foundList.innerHTML=[...found].sort((a,b)=>order(a)-order(b)).map(id=>`<li><button type="button" data-open="${id}"><strong>${no(id)}</strong> ${esc(title(id))}</button></li>`).join("")}function view(id){cur=id;mark(id);doc(byId(id)||base.home);tabs.forEach(t=>t.classList.toggle("is-active",t.dataset.view===cur));list()}function record(id){view(id);close();scrollTo({top:0,behavior:"smooth"})}function show(t,b){mt.textContent=t;mb.innerHTML=b;modal.hidden=false}function close(){modal.hidden=true}function search(raw){let q=raw.trim().replace(/\s+/g,"");if(!q)return show("请输入关键词","<p>纸马铺的账册很旧，空白是查不出东西的。</p>");if(!/^[\u4e00-\u9fff]+$/.test(q))return show("关键词格式不对","<p>这里只认连续的中文关键词。不要输入空格、英文、数字或标点。</p><p>例：<strong>沈婉</strong>、<strong>河门</strong>、<strong>纸马</strong></p>");let rs=kw.get(q)||[];if(!rs.length)return show("没有找到相关记录",`<p>旧账里没有“<strong>${esc(q)}</strong>”。也可能是字不对，或这个词还没在你发现的页面里出现。</p>`);rs.forEach(r=>mark(r.id));list();show("搜索结果",`<p>共有 <strong>${rs.length}</strong> 项符合条件的结果：</p>`+rs.map(r=>`<div class="result-item"><p class="page-no">${r.no}</p><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><button class="result-link" type="button" data-open="${r.id}">打开档案</button></div>`).join(""))}
$("#search-form").addEventListener("submit",e=>{e.preventDefault();search(input.value)});$(".shop-tabs").addEventListener("click",e=>{let b=e.target.closest("[data-view]");if(b)view(b.dataset.view)});foundList.addEventListener("click",e=>{let b=e.target.closest("[data-open]");if(b)record(b.dataset.open)});modal.addEventListener("click",e=>{let c=e.target.closest("[data-close]"),o=e.target.closest("[data-open]");if(c)close();if(o)record(o.dataset.open)});addEventListener("keydown",e=>{if(e.key==="Escape")close()});$("#show-intro").addEventListener("click",()=>show("引言","<p>你叫沈知遥。2026年七月，你收到一封没有寄件地址的快递，里面只有一张三年前的纸马铺收据。</p><p>收据付款人是失踪的表姐沈婉，取货人却写着你的名字。背面那句话只有八个字：别让他们开河门。</p><p>你打开临溪纸马铺的旧网站，准备从沈婉、河门、纸马三个词开始查起。</p>"));$("#reset-progress").addEventListener("click",()=>{found=["home","goods","notice","room"];save();view("home");show("进度已清空","<p>浏览器里的发现记录已清空。文件没有被删除。</p>")});$("#share-game").addEventListener("click",async()=>{let url=location.href,isFile=location.protocol==="file:",isLocal=["localhost","127.0.0.1"].includes(location.hostname);if(!isFile&&navigator.share){try{return await navigator.share({title:"临溪纸马铺",text:"一个通过搜索中文关键词推进的民俗悬疑网站小游戏。",url})}catch{}}let copied=false;if(!isFile&&navigator.clipboard){try{await navigator.clipboard.writeText(url);copied=true}catch{}}show("分享给别人玩",`<div class="share-box">${isFile?`<p class="share-warning">你现在是直接打开本机文件。这个 file:// 地址发给别人打不开。要给别人玩，请发布成公网链接。</p>`:isLocal?`<p class="share-warning">你现在用的是本机预览地址。别人通常打不开。请发布成公网链接。</p>`:`<p>${copied?"链接已复制。":"复制下面链接发给别人即可。"}</p>`}<input class="share-url" readonly value="${esc(url)}"><p>手机和电脑都可以玩；HTTPS 下可添加到主屏幕。</p></div>`)});addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#install-game").hidden=false});$("#install-game").addEventListener("click",async()=>{if(!installPrompt)return show("安装提示","<p>当前浏览器暂时没有提供安装入口。发布到 HTTPS 后，可在手机浏览器菜单中选择添加到主屏幕。</p>");installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("#install-game").hidden=true});if("serviceWorker"in navigator&&location.protocol!=="file:")addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));view("home");